FROM wallysoc/toolchains_wally

ENV QUESTA=/cad/mentor/questa_sim-xxxx.x_x
ENV RUN_QUESTA=false
ENV USERNAME=cad

VOLUME [ "/home/${USERNAME}/cvw" ]
USER root

COPY --chown=${USERNAME}:${USERNAME} . /home/${USERNAME}
RUN chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}
RUN chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/cvw

USER ${USERNAME}
WORKDIR /home/${USERNAME}/cvw

CMD [ "/bin/sh", "-c", "/home/${USERNAME}/run_regression.sh" ]