#!/usr/bin/bash

# sim-testfloat-verilator
# David_Harris@hmc.edu 3 April 2024 
# Run Testfloat simulations with Verilator
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1

# cvtint - test integer conversion unit (fcvtint)
# cvtfp  - test floating-point conversion unit (fcvtfp)
# cmp    - test comparison unit's LT, LE, EQ opperations (fcmp)
# add    - test addition
# fma    - test fma
# mul    - test mult with fma
# sub    - test subtraction
# div    - test division
# sqrt   - test square root
# all    - test everything

wsim fdqh_ieee_rv64gc add --tb testbench_fp --sim verilator

# Change TEST_SIZE to only test certain FP width
# values are QP, DP, SP, HP or all for all tests
#vsim -voptargs=+acc work.testbenchfp -GTEST=$2 -GTEST_SIZE="all" 
